-- ZetaAdvancedGraphicSettingsUltraHighQuality.lua
local this={
  description="Zeta - Advanced Graphics Menu - Ultra High Quality",
  profile={
   	ZetaCustomSettingZetaAdvancedGraphicSettingsPointLightShadowResolution=13,
	ZetaCustomSettingZetaAdvancedGraphicSettingsSpotLightShadowResolution=13,
	ZetaCustomSettingZetaAdvancedGraphicSettingsDirectionalLightShadowResolution=13,
	ZetaCustomSettingZetaAdvancedGraphicSettingsShadowCascadeRange=0,
	ZetaCustomSettingZetaAdvancedGraphicSettingsShadowCastingStaticLightCount=24,
	ZetaCustomSettingZetaAdvancedGraphicSettingsShadowCastingDynamicLightCount=8,
	ZetaCustomSettingZetaAdvancedGraphicSettingsCloneDrawDistance=2560,
	ZetaCustomSettingZetaAdvancedGraphicSettingsModelDrawDistance=2048,
	ZetaCustomSettingZetaAdvancedGraphicSettingsReduceMipmaps=0,
	ZetaCustomSettingZetaAdvancedGraphicSettingsEnableFXAA=1,
  }
}
return this